name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm 10
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node 24
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'

      - name: Clean install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: TypeScript type checking
        run: pnpm run typecheck

      - name: Run unit tests
        run: pnpm run test

      - name: Generate files
        run: pnpm run generate

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
